server:
  port: 5080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Not-a-professional/myspringcloudconfig # 远程仓库地址
          search-paths: /**
      label: master # 远程仓库的分支
  application:
    name: configserver
  rabbitmq:
      host: 106.12.19.58
      port: 5672
      username: admin
      password: admin
eureka:
  client:
    service-url:
      defaultZone: http://liwei:wwwliwei001com@localhost:2080/eureka
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh #SpringBoot2.0后Config客户端自动刷新时没有/actuator/bus-refresh节点，需要配置
                             #请求路径为localhost:5080/actuator/bus-refresh